repos:
  # Python Linting and Formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5 # Ensure this matches your desired Ruff version
    hooks:
      # Run the Ruff linter and automatically fix standard violations
      - id: ruff
        args: [--fix]
      # Run the Ruff formatter
      - id: ruff-format

  # TypeScript/JavaScript Linting
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: system
        types_or: [ts, tsx, javascript, jsx]
        pass_filenames: true
