services:
  ui:
    image: ghcr.io/system-b15/bluz/ui:${BLUZ_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluz-ui
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "hive.org:host-gateway"
    networks:
      - bluz_net
    depends_on:
      - curriculum-db
      - sessions

  curriculum-db:
    image: postgres:15-alpine
    container_name: bluz-curriculum-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: curriculum_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bluz_net

  sessions:
    image: ghcr.io/system-b15/bluz/sessions:${BLUZ_VERSION:-latest}
    build:
      context: session-server
      dockerfile: Dockerfile.websocket
    container_name: bluz-sessions
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bluz_net

  proxy:
    image: ghcr.io/system-b15/bluz/proxy:${BLUZ_VERSION:-latest}
    container_name: bluz-proxy
    restart: unless-stopped
    build:
      context: nginx
      dockerfile: Dockerfile.proxy
    ports:
      - "127.0.0.3:80:80"
      - "127.0.0.3:443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ui
      - sessions
    networks:
      - bluz_net

volumes:
  pgdata:

networks:
  bluz_net:
    driver: bridge
