
export const WEBSOCKET_SESSION_SERVER_PORT = parseInt(
  process.env.WEBSOCKET_SESSION_SERVER_PORT ?? "443",
  10,
);

export const WEBSOCKET_SESSION_SERVER_HOST =
  process.env.WEBSOCKET_SESSION_SERVER_HOST ?? "127.0.0.1";

export const SECURE_CONTEXT_ONLY =
  process.env.NODE_ENV === "production" ||
  WEBSOCKET_SESSION_SERVER_PORT === 443;

export const WEBSOCKET_PROTOCOL = SECURE_CONTEXT_ONLY ? "wss" : "ws";

export const WEBSOCKET_PORT_SUFFIX =
  WEBSOCKET_SESSION_SERVER_PORT === 443 || WEBSOCKET_SESSION_SERVER_PORT === 80
    ? ""
    : `:${WEBSOCKET_SESSION_SERVER_PORT}`;

export const NEXT_PUBLIC_WEBSOCKET_SESSION_SERVER_CONN_STRING = `${WEBSOCKET_PROTOCOL}://${WEBSOCKET_SESSION_SERVER_HOST}${WEBSOCKET_PORT_SUFFIX}/ws/`;
export const WEBSOCKET_SESSION_SERVER_SENDER_SERVER_MAGIC = "server";
export const WEBSOCKET_SESSION_SERVER_SENDER_AUTH_KEY =
  process.env.WEBSOCKET_SESSION_SERVER_SENDER_AUTH_KEY;

export enum MessageTypes
{
  REGISTER_SESSION = "register-session",
  REGISTER_SYNC_PROVIDER = "register-sync-provider",
  SYNC_OBJECT_UPDATE = "sync-object-update",
  DEREGISTER_SYNC_PROVIDER = "deregister-sync-provider",
  EVENT_DATA_UPDATE = "edu",
  EVENT_ADDED_OR_REMOVED = "ear",

  SETTINGS_UPDATE = "su",
  COURSES_UPDATE = "cu",
}
export const COMBO_DATA_KEY = "combo-data";
