import {
    GanttCurriculum,
    GanttCurriculumId,
    GanttCurriculumModuleDayMapping,
    GanttDay,
    GanttEvent,
    GanttModule,
    GanttModuleId,
    GanttSyllabus,
    GanttSyllabusId,
    GanttWeek,
    GanttWeekId,
} from "@/api-shared/types/gantt/models";
import {
    RelationalConstraint,
    TemporalConstraint,
} from "@/api-shared/types/gantt/models/constraint";

/**
 * Payload to create a new Gantt constraint: a relational or temporal
 * constraint. Neither `RelationalConstraint` nor `TemporalConstraint`
 * carries `createdAt`/`updatedAt` — those exist only on the DB row shape,
 * not this client-side model — so there is nothing to omit here.
 */
export type CreateConstraintPayload = RelationalConstraint | TemporalConstraint;

/**
 * Payload to create a new Curriculum.
 * - Omit 'id': Generated by the database.
 * - Omit 'syllabuses': A new curriculum starts with an empty array of syllabuses.
 */
export type CreateGanttCurriculumPayload = {
    // Weeks are created separately, new curriculum starts with empty weeks
} & Omit<GanttCurriculum, "id" | "syllabuses" | "weeks">;

/**
 * Payload to create a new Curriculum Week.
 * - Omit 'id': Generated by the database.
 * - Omit 'days': A new week starts with an empty array of days.
 * - Omit 'title': Generated from the week number.
 * - Add 'curriculumId': The foreign key to link this week to its parent curriculum.
 */
export type CreateGanttWeekPayload = {
    curriculumId: GanttCurriculumId;
} & Omit<GanttWeek, "days" | "id" | "title">;

/**
 * Payload to create a new Curriculum Day.
 * - Omit 'id': Generated by the database.
 * - Omit 'title': Generated from the day name.
 * - Add 'curriculumWeekId': The foreign key to link this day to its parent week.
 */
export type CreateGanttDayPayload = {
    weekId: GanttWeekId;
} & Omit<GanttDay, "id" | "title">;

/**
 * Payload to create a new Syllabus.
 * - Omit 'id': Generated by the database.
 * - Omit 'modules': A new syllabus starts with an empty array of modules.
 * - Add 'curriculumId': The foreign key to link this syllabus to its parent curriculum.
 */
export type CreateGanttSyllabusPayload = {
    curriculumId: GanttCurriculumId;
} & Omit<GanttSyllabus, "id" | "modules">;

/**
 * Payload to create a new Module.
 * - Omit 'id': Generated by the database.
 * - Omit 'events': A new module starts with an empty array of events.
 * - Add 'syllabusId': The foreign key to link this module to its parent syllabus.
 */
export type CreateGanttModulePayload = {
    syllabusId: GanttSyllabusId;
} & Omit<GanttModule, "constraints" | "events" | "id">;

/**
 * Payload to create a new Module Event.
 * - Omit 'id': Generated by the database.
 * - Add 'moduleId': The foreign key to link this event to its parent module.
 */
export type CreateGanttEventPayload = {
    moduleId: GanttModuleId;
} & Omit<GanttEvent, "constraints" | "id">;

export type CreateGanttCurriculumEventDayMapping = {} & Omit<
    GanttCurriculumModuleDayMapping,
    "curriculumId" | "id"
>;
