import {
  GanttCurriculum,
  GanttCurriculumId,
} from "@/api-shared/types/gantt/models/curriculum";
import { GanttCurriculumModuleDayMapping } from "@/api-shared/types/gantt/models/curriculum-day-module-mapping";
import { GanttDay } from "@/api-shared/types/gantt/models/day";
import { GanttEvent } from "@/api-shared/types/gantt/models/event";
import {
  GanttModule,
  GanttModuleId,
} from "@/api-shared/types/gantt/models/module";
import {
  GanttSyllabus,
  GanttSyllabusId,
} from "@/api-shared/types/gantt/models/syllabus";
import { GanttWeek, GanttWeekId } from "@/api-shared/types/gantt/models/week";

/**
 * Payload to create a new Curriculum.
 * - Omit 'id': Generated by the database.
 * - Omit 'syllabuses': A new curriculum starts with an empty array of syllabuses.
 */
export interface CreateGanttCurriculumPayload extends Omit<
  GanttCurriculum,
  "id" | "syllabuses" | "weeks"
> {
  // Weeks are created separately, new curriculum starts with empty weeks
}

/**
 * Payload to create a new Curriculum Week.
 * - Omit 'id': Generated by the database.
 * - Omit 'days': A new week starts with an empty array of days.
 * - Omit 'title': Generated from the week number.
 * - Add 'curriculumId': The foreign key to link this week to its parent curriculum.
 */
export interface CreateGanttWeekPayload extends Omit<
  GanttWeek,
  "days" | "id" | "title"
> {
  curriculumId: GanttCurriculumId;
}

/**
 * Payload to create a new Curriculum Day.
 * - Omit 'id': Generated by the database.
 * - Omit 'title': Generated from the day name.
 * - Add 'curriculumWeekId': The foreign key to link this day to its parent week.
 */
export interface CreateGanttDayPayload extends Omit<GanttDay, "id" | "title"> {
  weekId: GanttWeekId;
}

/**
 * Payload to create a new Syllabus.
 * - Omit 'id': Generated by the database.
 * - Omit 'modules': A new syllabus starts with an empty array of modules.
 * - Add 'curriculumId': The foreign key to link this syllabus to its parent curriculum.
 */
export interface CreateGanttSyllabusPayload extends Omit<
  GanttSyllabus,
  "id" | "modules"
> {
  curriculumId: GanttCurriculumId;
}

/**
 * Payload to create a new Module.
 * - Omit 'id': Generated by the database.
 * - Omit 'events': A new module starts with an empty array of events.
 * - Add 'syllabusId': The foreign key to link this module to its parent syllabus.
 */
export interface CreateGanttModulePayload extends Omit<
  GanttModule,
  "events" | "id"
> {
  syllabusId: GanttSyllabusId;
}

/**
 * Payload to create a new Module Event.
 * - Omit 'id': Generated by the database.
 * - Add 'moduleId': The foreign key to link this event to its parent module.
 */
export interface CreateGanttEventPayload extends Omit<GanttEvent, "id"> {
  moduleId: GanttModuleId;
}

export interface CreateGanttCurriculumModuleDayMapping extends Omit<
  GanttCurriculumModuleDayMapping,
  "curriculumId" | "id"
> {}
