import { ClientApiError } from "@/api-shared/errors";
import { CutValidationError } from "@/api-shared/gantt/cut-planner";
import { ModuleEventType } from "@/api-shared/types/gantt/models";

/**
 * API contract for the curriculum → schedule cut ("גזירה ללו"ז", #118).
 * The endpoint materializes a published curriculum's gantt data into schedule
 * events in the linked iteration's MongoDB. All inputs are derived server-side
 * from the curriculum id, so the request carries no payload.
 */

export type ApiCurriculumCutPayload = void;

export type ApiCurriculumCutResponse = {
    /** Number of schedule events created. */
    createdEvents: number;
    /** Courses that were newly created for shuffles during the cut. */
    createdCourses: Array<{ id: string; name: string }>;
    /** Occurrences that overlap each other after stacking (informational). */
    overlaps: number;
};

/**
 * A single dated, timed occurrence in a cut preview — the pure planner's
 * output enriched with display metadata. Dates are ISO strings so the payload
 * survives JSON transport; the client re-hydrates with dayjs.
 */
export type ApiCutPreviewOccurrence = {
    ganttEventId: string;
    title: string;
    /** ModuleEventType of the source gantt event. */
    eventType: ModuleEventType;
    syllabusTitle: string;
    moduleTitle: string;
    /** ISO date (yyyy-MM-dd) of the occurrence. */
    occurrenceDate: string;
    /** ISO datetime. */
    startTime: string;
    /** ISO datetime. */
    endTime: string;
    /** True when this is a recurrence echo rather than the mapped start day. */
    isRecurrenceEcho: boolean;
};

/**
 * Response of GET .../cut/preview — a dry-run of the cut planner. Never
 * writes. `ok: false` carries the planner's validation errors (e.g. missing
 * start date) so the preview UI can explain why nothing renders.
 */
export type ApiCurriculumCutPreviewResponse =
    | { ok: false; errors: Array<CutValidationError> }
    | {
          ok: true;
          occurrences: Array<ApiCutPreviewOccurrence>;
          overlaps: number;
          /**
           * Events the real cut would reject (unmapped / unsatisfied
           * recurrence) that the preview skipped instead of failing on.
           */
          skipped: Array<CutValidationError>;
      };

/**
 * Cut status for a curriculum, driving the UI toggle between the "cut" and
 * "pull back" actions. `cut` is true when the linked iteration holds any live
 * (non-archived) cut event.
 */
export type ApiCurriculumCutStatus = {
    cut: boolean;
    /** Number of live cut events in the linked iteration. */
    count: number;
};

/**
 * Response for a pull-back: the schedule events generated by a previous cut are
 * soft-deleted (archived) from the linked iteration.
 */
export type ApiCurriculumPullBackResponse = {
    /** Number of schedule events that were soft-deleted. */
    removedEvents: number;
};

/** Structured error codes returned when a cut is rejected without writing. */
export type CurriculumCutErrorCode =
    | "already-cut"
    | "draft"
    | "invalid-plan"
    | "no-iteration";

/** Structured error codes returned when a pull-back is rejected. */
export type CurriculumPullBackErrorCode = "no-iteration" | "not-cut";

export type ApiCurriculumPullBackError = {
    code: CurriculumPullBackErrorCode;
    /** Human-readable Hebrew message describing the rejection. */
    message?: string;
};

export type ApiCurriculumCutError = {
    code: CurriculumCutErrorCode;
    /** Present for `invalid-plan`: the pure planner's collected validation errors. */
    errors?: Array<CutValidationError>;
    /** Present for `already-cut`: how many cut events already exist in the iteration. */
    count?: number;
    /** Human-readable Hebrew message describing the rejection. */
    message?: string;
};

/**
 * Thrown by the client wrapper when a cut is rejected. Carries the full
 * structured payload (code + planner validation errors + already-cut count)
 * so the UI can render a specific message or validation list instead of a
 * generic network error. Extends {@link ClientApiError} so it flows through
 * the shared snackbar handling.
 */
export class CurriculumCutError
    extends ClientApiError
    implements ApiCurriculumCutError
{
    readonly code: CurriculumCutErrorCode;
    readonly errors?: Array<CutValidationError>;
    readonly count?: number;

    constructor(payload: ApiCurriculumCutError) {
        super(payload.message ?? 'גזירת הגאנט ללו"ז נכשלה');
        this.name = "CurriculumCutError";
        this.code = payload.code;
        this.errors = payload.errors;
        this.count = payload.count;
    }
}

/** Narrows a caught {@link ClientApiError} to one carrying a cut error code. */
export function isCurriculumCutErrorPayload(
    error: ClientApiError,
): error is ClientApiError & ApiCurriculumCutError {
    return typeof (error as Partial<ApiCurriculumCutError>).code === "string";
}

/**
 * Thrown by the client wrapper when a pull-back is rejected. Carries the coded
 * reason (no linked iteration / nothing to pull back) so the dialog can render
 * a specific Hebrew message instead of a generic network error.
 */
export class CurriculumPullBackError
    extends ClientApiError
    implements ApiCurriculumPullBackError
{
    readonly code: CurriculumPullBackErrorCode;

    constructor(payload: ApiCurriculumPullBackError) {
        super(payload.message ?? 'משיכת הלו"ז חזרה נכשלה');
        this.name = "CurriculumPullBackError";
        this.code = payload.code;
    }
}

/** Narrows a caught {@link ClientApiError} to one carrying a pull-back code. */
export function isCurriculumPullBackErrorPayload(
    error: ClientApiError,
): error is ClientApiError & ApiCurriculumPullBackError {
    return typeof (error as Partial<ApiCurriculumPullBackError>).code === "string";
}
