import { Curriculum, CurriculumDay, CurriculumId, CurriculumWeek, CurriculumWeekId, Module, ModuleEvent, ModuleId, Syllabus, SyllabusId } from "@/api-shared/types/gant/curriculum";

/**
 * Payload to create a new Curriculum.
 * - Omit 'id': Generated by the database.
 * - Omit 'syllabuses': A new curriculum starts with an empty array of syllabuses.
 */
export interface CreateCurriculumPayload extends Omit<Curriculum, 'id' | 'syllabuses' | 'weeks'>
{
    // Weeks are created separately, new curriculum starts with empty weeks
}

/**
 * Payload to create a new Curriculum Week.
 * - Omit 'id': Generated by the database.
 * - Omit 'days': A new week starts with an empty array of days.
 * - Add 'curriculumId': The foreign key to link this week to its parent curriculum.
 */
export interface CreateCurriculumWeekPayload extends Omit<CurriculumWeek, 'id' | 'days'>
{
    curriculumId: CurriculumId;
}

/**
 * Payload to create a new Curriculum Day.
 * - Omit 'id': Generated by the database.
 * - Add 'curriculumWeekId': The foreign key to link this day to its parent week.
 */
export interface CreateCurriculumDayPayload extends Omit<CurriculumDay, 'id'>
{
    curriculumWeekId: CurriculumWeekId;
}

/**
 * Payload to create a new Syllabus.
 * - Omit 'id': Generated by the database.
 * - Omit 'modules': A new syllabus starts with an empty array of modules.
 * - Add 'curriculumId': The foreign key to link this syllabus to its parent curriculum.
 */
export interface CreateSyllabusPayload extends Omit<Syllabus, 'id' | 'modules'>
{
    curriculumId: CurriculumId;
}

/**
 * Payload to create a new Module.
 * - Omit 'id': Generated by the database.
 * - Omit 'events': A new module starts with an empty array of events.
 * - Add 'syllabusId': The foreign key to link this module to its parent syllabus.
 */
export interface CreateModulePayload extends Omit<Module, 'events' | 'id'>
{
    syllabusId: SyllabusId;
}

/**
 * Payload to create a new Module Event.
 * - Omit 'id': Generated by the database.
 * - Add 'moduleId': The foreign key to link this event to its parent module.
 */
export interface CreateModuleEventPayload extends Omit<ModuleEvent, 'id'>
{
    moduleId: ModuleId;
}
