/**
 * Name: rest-docs.mjs
 * Purpose: Generates docs/rest-api.md, the REST endpoint reference shipped
 *          in the offline bundle as API.md (#760), from ui/src/app/api routes.
 * Created: 2026-09-29
 * Author: Michael K. Steinberg
 *
 * Usage: node scripts/rest-docs.mjs          (write)
 *        node scripts/rest-docs.mjs --check  (exit 1 when stale)
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const HTTP_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"];
const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
export const API_ROOT = join(REPO, "ui", "src", "app", "api");
export const OUTPUT = join(REPO, "docs", "rest-api.md");

function findRoutes(dir) {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) return findRoutes(full);
        return entry.name === "route.ts" ? [full] : [];
    });
}

/** `[id]` → `{id}`, `[...nextauth]` → `{...nextauth}`. Route groups `(x)` drop out. */
export function toUrlPath(routeFile) {
    const segments = relative(API_ROOT, dirname(routeFile))
        .split(sep)
        .filter((s) => s && !/^\(.*\)$/.test(s))
        .map((s) => s.replace(/^\[(.*)\]$/, "{$1}"));
    return ["/api", ...segments].join("/");
}

/** HTTP methods a route module exports, in canonical order. */
export function exportedMethods(source) {
    const found = new Set();
    const direct = /export\s+(?:const|async\s+function|function)\s+([A-Z]+)\b/g;
    for (const [, name] of source.matchAll(direct)) found.add(name);
    const named = /export\s*\{([^}]*)\}/g;
    for (const [, list] of source.matchAll(named)) {
        for (const part of list.split(",")) {
            const name = part.trim().split(/\s+as\s+/).pop()?.trim();
            if (name) found.add(name);
        }
    }
    return HTTP_METHODS.filter((m) => found.has(m));
}

export function collectEndpoints(root = API_ROOT) {
    return findRoutes(root)
        .map((file) => ({ path: toUrlPath(file), methods: exportedMethods(readFileSync(file, "utf8")) }))
        .filter((e) => e.methods.length > 0)
        .sort((a, b) => a.path.localeCompare(b.path));
}

export function renderRestDocs(endpoints = collectEndpoints()) {
    const groups = new Map();
    for (const e of endpoints) {
        const group = e.path.split("/")[2] ?? "";
        if (!groups.has(group)) groups.set(group, []);
        groups.get(group).push(e);
    }
    const lines = [
        "# REST API",
        "",
        "<!-- Generated by scripts/rest-docs.mjs. Do not edit by hand: run `npm run docs:rest`. -->",
        "",
        "Every endpoint the Bluz server exposes. All paths are relative to the app's",
        "base URL (e.g. `https://bluz.local`). Requests need a signed-in session, or a",
        "CLI token (`bluz login`). Responses are JSON:",
        "`{ \"status\": 0, \"data\": ... }` on success, a non-zero `status` with `error` otherwise.",
        "",
        "`{id}` marks a path parameter.",
        "",
        "For the TypeScript client and server modules, see the online reference:",
        "<https://system-b90.github.io/.github/bluz/api/>.",
        "",
    ];
    for (const [group, items] of groups) {
        lines.push(`## ${group}`, "", "| Methods | Path |", "| --- | --- |");
        for (const e of items) lines.push(`| ${e.methods.join(", ")} | \`${e.path}\` |`);
        lines.push("");
    }
    return lines.join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
    const markdown = renderRestDocs();
    const outputs = [
        [OUTPUT, markdown],
    ];
    if (process.argv.includes("--check")) {
        const stale = outputs.filter(
            ([file, text]) => readFileSync(file, "utf8").replace(/\r\n/g, "\n") !== text,
        );
        for (const [file] of stale) console.error(`${relative(REPO, file)} is stale. Run: npm run docs:rest`);
        if (stale.length > 0) process.exit(1);
    } else {
        for (const [file, text] of outputs) writeFileSync(file, text);
    }
}
