#!/bin/sh
set -e

# Run database migrations
if [ "$NODE_ENV" = "development" ]; then
    echo "Running migrations for Development..."
    # Execute the raw TypeScript file directly since we have the full source
    # npx tsx ui/src/api-server/drizzle-migrate.ts
else
    echo "Running migrations for Production..."
    # Execute the compiled JavaScript file generated by the builder stage if present
    if [ -f "/app/migrate.js" ]; then
        node /app/migrate.js
    else
        echo "Production migration script (/app/migrate.js) not found. Skipping migrations."
    fi
fi

# Execute the main container command (CMD)
exec "$@"