#!/bin/sh
set -e

# Run database migrations
if [ "$NODE_ENV" = "development" ]; then
    echo "Running migrations for Development..."
    # Execute the raw TypeScript file directly since we have the full source
    # npx tsx ui/src/api-server/drizzle-migrate.ts
else
    echo "Running migrations for Production..."
    # Execute the compiled JavaScript file generated by the builder stage
    node /app/migrate.js
fi

# Execute the main container command (CMD)
exec "$@"