#!/bin/sh
set -e

# Run database migrations
if [ "$NODE_ENV" = "development" ]; then
    echo "Running migrations for Development..."
    # Execute the raw TypeScript file directly since we have the full source.
    # --tsconfig is required: tsx's tsconfig auto-discovery does not walk up
    # from the entry file when run with cwd=/app (the repo root, which has no
    # tsconfig.json of its own) -- without it, "@/*" never resolves and every
    # "@/..." import in this script fails with MODULE_NOT_FOUND.
    npx tsx --tsconfig ui/tsconfig.json ui/src/api-server/drizzle-migrate.ts
else
    echo "Running migrations for Production..."
    # Execute the compiled JavaScript file generated by the builder stage if present
    if [ -f "/app/migrate.js" ]; then
        node /app/migrate.js
    else
        echo "Production migration script (/app/migrate.js) not found. Skipping migrations."
    fi
fi

# Execute the main container command (CMD)
exec "$@"